### ISSUE TITLE
the code style....

### ISSUE THREAD

**Issue by AsuradaYuci** [rshivansh/Video-based-Person-Re-identification-Using-Spatial-Temporal-Attention-Networks#1]
to be honest,i think you should have to Check your code, please follow the pep-8 guidelines.

**Comment by AsuradaYuci** [comment]
> to be honest,i think you should have to Check your code, please follow the pep-8 guidelines.

sdfsds

**Comment by wengdunfang** [comment]
Sorry to bother you, but your code is not complete. can you updating it
